"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path

# ---------------------------------------------------------

# Rutas del proyecto

# ---------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------

# Seguridad

# ---------------------------------------------------------

SECRET_KEY = "django-insecure-y&(a%a_!a_^y*p2rqdtm@z_r^rf833h9v0phn3!2kw8o_de9d^"

DEBUG = True

ALLOWED_HOSTS = []

# ---------------------------------------------------------

# Aplicaciones instaladas

# ---------------------------------------------------------

INSTALLED_APPS = [
"django.contrib.admin",
"django.contrib.auth",
"django.contrib.contenttypes",
"django.contrib.sessions",
"django.contrib.messages",
"django.contrib.staticfiles",


# Aplicación del proyecto
"blog",

]

# ---------------------------------------------------------

# Middleware

# ---------------------------------------------------------

MIDDLEWARE = [
"django.middleware.security.SecurityMiddleware",
"django.contrib.sessions.middleware.SessionMiddleware",
"django.middleware.common.CommonMiddleware",
"django.middleware.csrf.CsrfViewMiddleware",
"django.contrib.auth.middleware.AuthenticationMiddleware",
"django.contrib.messages.middleware.MessageMiddleware",
"django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ---------------------------------------------------------

# URLs

# ---------------------------------------------------------

ROOT_URLCONF = "config.urls"

# ---------------------------------------------------------

# Templates

# ---------------------------------------------------------

TEMPLATES = [
{
"BACKEND": "django.template.backends.django.DjangoTemplates",

    # Si más adelante agregas una carpeta global templates/,
    # Django la reconocerá automáticamente.
    "DIRS": [
        BASE_DIR / "templates",
    ],

    "APP_DIRS": True,

    "OPTIONS": {
        "context_processors": [
            "django.template.context_processors.request",
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
        ],
    },
},


]

# ---------------------------------------------------------

# WSGI

# ---------------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"

# ---------------------------------------------------------

# Base de datos

# ---------------------------------------------------------

DATABASES = {
"default": {
"ENGINE": "django.db.backends.sqlite3",
"NAME": BASE_DIR / "db.sqlite3",
}
}

# ---------------------------------------------------------

# Validadores de contraseña

# ---------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
{
"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
},
{
"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
},
{
"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
},
{
"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
},
]

# ---------------------------------------------------------

# Internacionalización

# ---------------------------------------------------------

LANGUAGE_CODE = "es-cl"

TIME_ZONE = "America/Santiago"

USE_I18N = True

USE_TZ = True

# ---------------------------------------------------------

# Archivos estáticos

# ---------------------------------------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [
BASE_DIR / "static",
]

# ---------------------------------------------------------

# Login y Logout

# ---------------------------------------------------------

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "lista_articulos"

LOGOUT_REDIRECT_URL = "lista_articulos"

# ---------------------------------------------------------

# Clave primaria por defecto

# ---------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
